/** Libellés lisibles du journal d'audit pour l'activité récente. */
export const ACTIVITY_LABEL: Record<string, string> = {
  "user.registered": "Compte créé",
  "onboarding.completed": "Onboarding terminé",
  "client.created": "Client ajouté",
  "client.updated": "Client modifié",
  "client.deleted": "Client supprimé",
  "client.exported": "Données d'un client exportées",
  "client.match.merged": "Clients fusionnés",
  "client.match.ignored": "Correspondance ignorée",
  "content.created": "Contenu ajouté",
  "content.metrics.added": "Métriques de contenu ajoutées",
  "social.snapshot.added": "Snapshot réseau ajouté",
  "import.planity.completed": "Import Planity",
  "import.rolled_back": "Import annulé",
  "revenue.manual.created": "Revenu saisi",
  "appointment.manual.created": "Rendez-vous saisi",
  "mission.updated": "Mission mise à jour",
  "demo.loaded": "Données DEMO chargées",
  "demo.reset": "Données DEMO réinitialisées",
  "data.exported": "Export de données",
  "ai.coach.asked": "Question au coach IA",
  "goal.updated": "Objectif mis à jour",
  "settings.updated": "Réglages modifiés",
};
